wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_1.txt -b 
wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_2.txt -b 
wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_3.txt -b 
wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_4.txt -b 
wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_5.txt -b 
wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_6.txt -b 
wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_7.txt -b 
wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_8.txt -b 
wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_9.txt -b 
wosedon -c /mnt/data/repos/plukb/wosedon/cfg/pkedzia.ini -f /mnt/data/korpusy/kpwr-1.1_wsd_+_disamb/index_wsd_pelnasciezka_10.txt -b 
