FIND_LIBRARY(CORPUS_LIBRARY NAMES corpus PATH /usr/lib /usr/local/lib)
MARK_AS_ADVANCED(CORPUS_LIBRARY)


IF (CORPUS_LIBRARY)
   SET(CORPUS_FOUND TRUE)
ENDIF (CORPUS_LIBRARY)


IF (CORPUS_FOUND)
   IF (NOT Corpus_FIND_QUIETLY)
      MESSAGE(STATUS "Found Corpus: ${CORPUS_LIBRARY}")
   ENDIF (NOT Corpus_FIND_QUIETLY)
ELSE (CORPUS_FOUND)
   IF (Corpus_FIND_REQUIRED)
      MESSAGE(STATUS "Could not find Corpus")
   ENDIF (Corpus_FIND_REQUIRED)
ENDIF (CORPUS_FOUND)
