
install: 
	mkdir -p /usr/share/eniam/theories
	mkdir -p /usr/share/eniam/theories/numbers
	cp numbers/*  /usr/share/eniam/theories/numbers
	mkdir -p /usr/share/eniam/theories/persons
	cp persons/*  /usr/share/eniam/theories/persons

